pgadmin4:
  servicePort: &servicePort 5050
  enabled: true
  fullnameOverride: pgadmin
  env:
    email:  pgadmin # email or nickname
  envVarsExtra:
    - name: PGADMIN_DISABLE_POSTFIX
      value: "1"
    - name: PGADMIN_LISTEN_PORT
      value: "5050"

  securityContext: ""
  containerSecurityContext:
    enabled: false
  # disabled initContainer
  VolumePermissions:
    enabled: false
  
  persistentVolume:
    size: 100Mi
  
  containerPorts:
    http: *servicePort
  service:
    type: ClusterIP
    port: *servicePort
    targetPort: *servicePort
  ingress:
    enabled: true
    hosts:
      - host: pgadmin-cnpgexample.apps.app1.numerique-interieur.com
        paths:
          - path: /
            pathType: Prefix
  resources:
    requests:
      memory: "128Mi"
      cpu: "250m"
    limits:
      memory: "256Mi"
      cpu: "500m"

  strategy:
    type: Recreate
  existingSecret: pgadmin4-password

db:
  backup:
    enabled: false
    schedule: "0 0 * * * *"
    retentionPolicy: 30d
    endpointURL: "http://minio:9000"
    destinationPath: "s3://database"
    awsCredentialsSecret: aws-creds

  resources:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 512Mi
      cpu: 500m